name: Check new upstream commits

on:
  repository_dispatch:
    types: [check_upstream]

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
      with:
        upstream_repository: i3/go-i3
        upstream_branch: master
        target_branch: master_upstream
        git_pull_args: --ff-only

    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits == 'true'
      run: curl -s -X POST --connect-timeout 10 https://api.telegram.org/bot${{secrets.API_KEY}}/sendMessage -d chat_id=${{secrets.CHAT_ID}} -d parse_mode="Markdown" -d text="New commit in upstream repo ${{github.repository}}"

